# Generated by Django 4.0.3 on 2022-04-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcripts',
            name='aa_change_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
