# Generated by Django 4.0.3 on 2022-04-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_genes_approved_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcripts',
            name='ensembl_canonical',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcripts',
            name='refseq_match_transcript_mane_plus_clinical',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcripts',
            name='refseq_match_transcript_mane_select',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcripts',
            name='transcript_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcripts',
            name='transcript_support_level',
            field=models.TextField(blank=True, null=True),
        ),
    ]
