# Generated by Django 4.0.3 on 2022-06-03 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_refseqhgvsc_hgvsc_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcript',
            old_name='reqseq_match',
            new_name='refseq_match',
        ),
    ]
