# Generated by Django 4.0.3 on 2022-06-06 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_lrgpeptide_peptide_id_refseqpeptide_hgvsp_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transcripts',
        ),
    ]
