# Generated by Django 4.0.3 on 2022-07-25 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_aminoacidtranscriptvariant_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ensemblpeptide',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='lrgpeptide',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='refseqpeptide',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ensemblpeptide',
            name='md5sum',
            field=models.TextField(default='8eb623106e02b96d9ccc11eb1678274f', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lrgpeptide',
            name='md5sum',
            field=models.TextField(default='8eb623106e02b96d9ccc11eb1678274f', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refseqpeptide',
            name='md5sum',
            field=models.TextField(default='8eb623106e02b96d9ccc11eb1678274f', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aminoacidtranscriptvariant',
            name='amino_acid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aa_transcript_variants', to='api.aminoacidchange'),
        ),
        migrations.AlterField(
            model_name='aminoacidtranscriptvariant',
            name='transcript',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aa_transcript_variants', to='api.transcript'),
        ),
        migrations.AlterField(
            model_name='aminoacidtranscriptvariant',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aa_transcript_variants', to='api.variants'),
        ),
    ]
