# Generated by Django 4.0.3 on 2022-07-30 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alfadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alfadata',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alfa', to='api.variants'),
        ),
    ]
