# Generated by Django 4.0.3 on 2022-07-31 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_alfadata_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='alfadata',
            name='variant_md5sum',
            field=models.TextField(default='127313560850215712742d68fff1ae85'),
            preserve_default=False,
        ),
    ]
