# Generated by Django 4.0.3 on 2022-08-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_alfadata_chrom_pos_ref_alt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alfadata',
            name='chrom_pos_ref_alt',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='alfadata',
            name='variant_md5sum',
            field=models.TextField(),
        ),
    ]
