# Generated by Django 4.0.3 on 2022-11-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_variants_transcripts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='transcripts',
            field=models.ManyToManyField(blank=True, related_name='variants', through='api.AminoAcidTranscriptVariant', to='api.transcript'),
        ),
    ]
