# Generated by Django 4.0.3 on 2022-11-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_variants_transcripts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dgidb',
            name='gene_name',
            field=models.TextField(),
        ),
    ]
