# Generated by Django 4.0.3 on 2022-11-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_cosmicgenomescreen_genome_wide_screen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aminoacidannotations',
            name='ds_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geneannotation',
            name='ds_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
