# Generated by Django 4.0.3 on 2022-04-02 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_genes_date_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genes',
            name='approved_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='genes',
            name='approved_symbol',
            field=models.TextField(blank=True, null=True),
        ),
    ]
