# Generated by Django 4.0.3 on 2022-04-11 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_transcripts_ensembl_canonical_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variants',
            name='gene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='api.genes'),
        ),
    ]
