# Generated by Django 4.0.3 on 2022-04-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_variants_gene'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcripts',
            name='md5sum',
            field=models.TextField(default='unversioned', unique=True),
            preserve_default=False,
        ),
    ]
