# Generated by Django 4.0.3 on 2022-05-11 15:35

from django.db import migrations, models

import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_transcripts_md5sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='genes',
            name='api_key',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
