# Generated by Django 4.0.3 on 2022-05-11 15:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220511_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genes',
            name='api_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
