# Generated by Django 4.0.3 on 2022-06-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_aminoacidannotations_aminoacidchange_ensemblhgvsc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refseqhgvsc',
            name='hgvsc_id',
            field=models.TextField(unique=True),
        ),
    ]
