# Generated by Django 4.0.3 on 2022-06-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_reqseq_match_transcript_refseq_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='lrgpeptide',
            name='peptide_id',
            field=models.TextField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refseqpeptide',
            name='hgvsp_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ensemblpeptide',
            name='hgvsp_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ensemblpeptide',
            name='peptide_id',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='lrgpeptide',
            name='hgvsp_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
