# Generated by Django 4.0.3 on 2022-06-07 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_delete_transcripts'),
    ]

    operations = [
        migrations.AddField(
            model_name='aminoacidannotations',
            name='gene',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='aa_annotations', to='api.genes'),
            preserve_default=False,
        ),
    ]
