# Generated by Django 4.0.3 on 2022-06-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_aminoacidannotations_gene'),
    ]

    operations = [
        migrations.AddField(
            model_name='aminoacidchange',
            name='genes',
            field=models.ManyToManyField(related_name='aa_changes', to='api.genes'),
        ),
    ]
