# Generated by Django 4.0.3 on 2022-06-15 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_aminoacidchange_genes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AminoAcidTranscriptVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='aminoacidchange',
            name='transcripts',
        ),
        migrations.AddField(
            model_name='aminoacidchange',
            name='transcript',
            field=models.ManyToManyField(blank=True, related_name='AminoAcidChange', through='api.AminoAcidTranscriptVariant', to='api.transcript'),
        ),
        migrations.AddField(
            model_name='transcript',
            name='canonical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='variants',
            name='amino_acid_changes',
            field=models.ManyToManyField(blank=True, related_name='variants', through='api.AminoAcidTranscriptVariant', to='api.aminoacidchange'),
        ),
        migrations.AlterField(
            model_name='ensemblpeptide',
            name='peptide_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lrgpeptide',
            name='peptide_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='refseqpeptide',
            name='peptide_id',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='ensemblpeptide',
            unique_together={('peptide_id', 'hgvsp_id')},
        ),
        migrations.AlterUniqueTogether(
            name='lrgpeptide',
            unique_together={('peptide_id', 'hgvsp_id')},
        ),
        migrations.AlterUniqueTogether(
            name='refseqpeptide',
            unique_together={('peptide_id', 'hgvsp_id')},
        ),
        migrations.AddField(
            model_name='aminoacidtranscriptvariant',
            name='amino_acid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aminoacidchange'),
        ),
        migrations.AddField(
            model_name='aminoacidtranscriptvariant',
            name='transcript',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.transcript'),
        ),
        migrations.AddField(
            model_name='aminoacidtranscriptvariant',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.variants'),
        ),
        migrations.RemoveField(
            model_name='ensemblpeptide',
            name='canonical',
        ),
    ]
