# Generated by Django 4.0.3 on 2022-07-31 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alfadata_variant_md5sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='alfadata',
            name='chrom_pos_ref_alt',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
