# Generated by Django 4.0.3 on 2022-08-01 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alfadata_chrom_pos_ref_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alfadata',
            name='chrom_pos_ref_alt',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='alfadata',
            name='variant_md5sum',
            field=models.TextField(db_index=True),
        ),
    ]
