# Generated by Django 4.0.3 on 2022-10-31 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_alfadata_chrom_pos_ref_alt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinvar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinvar_id', models.TextField()),
                ('qual', models.TextField(blank=True, null=True)),
                ('filter', models.TextField(blank=True, null=True)),
                ('af_esp', models.TextField(blank=True, null=True)),
                ('af_exac', models.TextField(blank=True, null=True)),
                ('af_tgp', models.TextField(blank=True, null=True)),
                ('alleleid', models.TextField(blank=True, null=True)),
                ('clndisdb', models.TextField(blank=True, null=True)),
                ('clndisdbincl', models.TextField(blank=True, null=True)),
                ('clndn', models.TextField(blank=True, null=True)),
                ('clndnincl', models.TextField(blank=True, null=True)),
                ('clnhgvs', models.TextField(blank=True, null=True)),
                ('clnrevstat', models.TextField(blank=True, null=True)),
                ('clnsig', models.TextField(blank=True, null=True)),
                ('clnsigconf', models.TextField(blank=True, null=True)),
                ('clnsigincl', models.TextField(blank=True, null=True)),
                ('clnvc', models.TextField(blank=True, null=True)),
                ('clnvcso', models.TextField(blank=True, null=True)),
                ('clnvi', models.TextField(blank=True, null=True)),
                ('dbvarid', models.TextField(blank=True, null=True)),
                ('geneinfo', models.TextField(blank=True, null=True)),
                ('mc', models.TextField(blank=True, null=True)),
                ('origin', models.TextField(blank=True, null=True)),
                ('rs_id', models.TextField(blank=True, null=True)),
                ('ssr', models.TextField(blank=True, null=True)),
                ('chrom_pos_ref_alt', models.TextField()),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinvar', to='api.variants')),
            ],
        ),
    ]
