# Generated by Django 4.0.3 on 2022-11-05 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_clinvar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='transcripts',
        ),
        migrations.AlterField(
            model_name='aminoacidchange',
            name='transcript',
            field=models.ManyToManyField(blank=True, related_name='amino_acid_changes', through='api.AminoAcidTranscriptVariant', to='api.transcript'),
        ),
        migrations.CreateModel(
            name='Dgidb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_name', models.TextField(unique=True)),
                ('gene_claim_name', models.TextField(blank=True, null=True)),
                ('interaction_claim_source', models.TextField(blank=True, null=True)),
                ('interaction_types', models.TextField(blank=True, null=True)),
                ('drug_claim_name', models.TextField(blank=True, null=True)),
                ('drug_claim_primary_name', models.TextField(blank=True, null=True)),
                ('drug_name', models.TextField(blank=True, null=True)),
                ('drug_concept_id', models.TextField(blank=True, null=True)),
                ('interaction_group_score', models.TextField(blank=True, null=True)),
                ('pmids', models.TextField(blank=True, null=True)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dgi_db', to='api.genes')),
            ],
        ),
    ]
