# Generated by Django 4.0.3 on 2022-11-08 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_clinvar_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annovardata',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annovar', to='api.variants'),
        ),
    ]
