# Generated by Django 4.0.3 on 2022-11-08 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_annovardata_avsnp_150_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annovardata',
            name='clnalleleid',
            field=models.TextField(blank=True, null=True),
        ),
    ]
